<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Risk</name>
   <tag></tag>
   <elementGuidId>587f5991-0494-491d-9430-eb6afbc94ff3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b3-l2-20_3-MenuId > div.padding-l-r-5px</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='b3-l2-20_3-MenuId']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>412dc5ad-00ca-4789-8579-c514103da8b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>padding-l-r-5px</value>
      <webElementGuid>46d2a725-22ce-4c50-b853-d66c695a254a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Risk</value>
      <webElementGuid>24de110d-e2db-407f-b8a7-185a9150fc24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-l2-20_3-MenuId&quot;)/div[@class=&quot;padding-l-r-5px&quot;]</value>
      <webElementGuid>d038d709-a474-43b7-99bb-57faea59f026</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='b3-l2-20_3-MenuId']/div</value>
      <webElementGuid>79c60cda-6185-4e56-b450-3432835a8b45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Savings and OCR'])[1]/following::div[1]</value>
      <webElementGuid>130f8db7-6d53-4ea6-b4bc-3c419e732f9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank Analysis'])[1]/following::div[1]</value>
      <webElementGuid>bc091abb-7d4a-4bf4-9347-09fecb18b596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CCV'])[1]/preceding::div[2]</value>
      <webElementGuid>18a4ffae-67fc-4380-b072-e685d182c8a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/div</value>
      <webElementGuid>7a9840d9-4beb-4b72-b7f3-de590d6c4177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Risk' or . = 'Risk')]</value>
      <webElementGuid>fc88258c-14e8-45e0-b280-6e83ab6ba018</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
