<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SubMenu_CCV</name>
   <tag></tag>
   <elementGuidId>bb921b3b-69ff-479f-ae46-6ace3ebcb5cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.custom-top-menu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;b3-l2-160_3-Menu2&quot;]/ul/div/li/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>758f64d3-d0c3-4a04-82c4-36cff52e4fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-top-menu</value>
      <webElementGuid>f6f7d1b7-a904-454f-b2c2-5071d47d8846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DashboardCustomer ProfileLoan/Sourcing &amp; RepaymentRemarks &amp; DeviationsSpecial ConditionsObservationsCrosslinkFinancial DetailsIncomeBureauObligationBank DetailsBank AnalysisSavings and OCRRiskCCVRisk ConsoleCust Search (Negative Scrubbing)PropertyKYCFile RequirementsDC CommentsOthersEmployer SearchProperty SearchCalculatorFee ComputationDocument Viewer</value>
      <webElementGuid>bd01c1de-e5f8-4904-a3bc-c4ff3ec94837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-PageLinks3&quot;)/ul[@class=&quot;custom-top-menu&quot;]</value>
      <webElementGuid>e15e887c-485b-41a6-92a8-005c1e33811f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-PageLinks3']/ul</value>
      <webElementGuid>35d05e75-93d2-431d-bb01-77efff221308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to Content (Press Enter)'])[1]/following::ul[1]</value>
      <webElementGuid>6b02829d-12a9-4822-aac5-904ad56f092d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul</value>
      <webElementGuid>550598c3-d24f-4146-ad96-0dd355fba03f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[(text() = 'DashboardCustomer ProfileLoan/Sourcing &amp; RepaymentRemarks &amp; DeviationsSpecial ConditionsObservationsCrosslinkFinancial DetailsIncomeBureauObligationBank DetailsBank AnalysisSavings and OCRRiskCCVRisk ConsoleCust Search (Negative Scrubbing)PropertyKYCFile RequirementsDC CommentsOthersEmployer SearchProperty SearchCalculatorFee ComputationDocument Viewer' or . = 'DashboardCustomer ProfileLoan/Sourcing &amp; RepaymentRemarks &amp; DeviationsSpecial ConditionsObservationsCrosslinkFinancial DetailsIncomeBureauObligationBank DetailsBank AnalysisSavings and OCRRiskCCVRisk ConsoleCust Search (Negative Scrubbing)PropertyKYCFile RequirementsDC CommentsOthersEmployer SearchProperty SearchCalculatorFee ComputationDocument Viewer')]</value>
      <webElementGuid>a3478900-6d00-4e98-832b-cc2a35ffae5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
