<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Textbox_CCVFileNo</name>
   <tag></tag>
   <elementGuidId>c9828b6e-3535-4612-8689-d3193a4c4360</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b7-InputFileNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b7-InputFileNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f78dc083-c834-49cd-b7ba-25b121be8f9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c4df5394-01a2-4e6b-92b2-1e36b857cd5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control displayinline height30px OSFillParent</value>
      <webElementGuid>21acdc7d-bc61-4658-be6a-a9099e697193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>File No</value>
      <webElementGuid>475120c7-183d-4924-bf0f-1dddb8c1a3e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>62af8f3c-b02e-45db-8288-9ba820510a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>9223372036854775807</value>
      <webElementGuid>89598454-de7f-4f69-bff4-274012a5ec2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b7-InputFileNo</value>
      <webElementGuid>7443269f-cd3a-49b0-b28e-c453f249cea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b7-InputFileNo&quot;)</value>
      <webElementGuid>dfcaaae4-d385-41cf-be89-1e468759c410</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b7-InputFileNo']</value>
      <webElementGuid>fbb5c257-a9dd-43aa-a402-365d0b74d45b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b7-b1-Content']/div/div/span[2]/input</value>
      <webElementGuid>45d15274-177a-4946-885f-ec6d7994f1fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>ba39aff9-0c01-41c5-9edd-c8dd57993bee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
